export const materials = new Map([
  [
    "wanderersadvice",
    {
      name: "Wanderer's Advice",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/6/60/Item_Wanderer%27s_Advice.png/revision/latest/scale-to-width-down/256?cb=20201116222406",
      description:
        "Character EXP material. Gives 1,000 EXP. These experiences are still beneficial even if one does not live in Teyvat.",
      itemType: "Character EXP Material",
      color: "RANDOM",
      rarity: "⭐⭐",
      source:
        "1.) Adventure and Exploration Reward\n2.) Ley Line Outcrops Blossom of Revelation",
      crafting: "No",
      forging: "No",
      cooking: "No",
    },
  ],
  [
    "adventurersexperience",
    {
      name: "Adventurer's Experience",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/0/07/Item_Adventurer%27s_Experience.png/revision/latest/scale-to-width-down/256?cb=20201116222310",
      description:
        "Character EXP material. Gives 5,000 EXP. These experiences are very beneficial for journeys into the unknown.",
      itemType: "Character EXP Material",
      color: "RANDOM",
      rarity: "⭐⭐⭐",
      source:
        "1.) Adventure and Exploration Reward\n2.) Paimon's Bargains\n3.) Ley Line Outcrops Blossom of Revelation",
      crafting: "No",
      forging: "No",
      cooking: "No",
    },
  ],
  [
    "heroswit",
    {
      name: "Hero's Wit",
      image:
        "https://static.wikia.nocookie.net/gensin-impact/images/2/26/Item_Hero%27s_Wit.png/revision/latest/scale-to-width-down/256?cb=20201116222208",
      description:
        "Character EXP material. Gives 20,000 EXP. These experiences are extremely precious for a pilgrim traveling through Teyvat in order to be closer to Celestia.",
      itemType: "Character EXP Material",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐",
      source:
        "1.) Random Event Reward\n2.) Ley Line Outcrops Blossom of Revelation (AR 35+)\n3.) Quest completion reward",
      crafting: "No",
      forging: "No",
      cooking: "No",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
  [
    "",
    {
      name: "",
      image: "",
      description: "",
      color: "RANDOM",
      rarity: "⭐⭐⭐⭐⭐",
      source: "",
      crafting: "",
      forging: "",
      cooking: "",
    },
  ],
]);
